# Generated by Django 4.1.5 on 2023-07-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
