# Generated by Django 4.1.5 on 2023-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_allfiles_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
