# Generated by Django 4.1.5 on 2023-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfiles',
            name='file',
            field=models.FileField(default='', upload_to='all_files/'),
        ),
    ]
