# Generated by Django 4.1.5 on 2023-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_folder_allfiles_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfiles',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
