# Generated by Django 4.1.5 on 2023-07-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_allfiles_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfiles',
            name='caption',
        ),
    ]
